name: Elixir NIF Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'elixir@v*'

permissions:
  attestations: write
  contents: write
  id-token: write

jobs:
  release:
    uses: leandrocp/github-actions/.github/workflows/nif-release.yml@main
    with:
      project-name: lumis_nif
      project-dir: packages/elixir/lumis/native/lumis_nif
      working-directory: packages/elixir/lumis
