name: Update Themes

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/update_themes.yml"

jobs:
  update-themes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - name: Install Neovim
        run: |
          sudo add-apt-repository ppa:neovim-ppa/unstable -y
          sudo apt-get update
          sudo apt-get install -y lua neovim

      - run: just gen-themes true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update themes"
          title: "chore: themes"
          body: |
            Automated PR to update themes.

            This PR was created automatically by the update-themes workflow.
          branch: update-themes
          delete-branch: true
          base: main
